//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM.FRS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public double CascadeClassifierScaleFactor {
            get {
                return ((double)(this["CascadeClassifierScaleFactor"]));
            }
            set {
                this["CascadeClassifierScaleFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CascadeClassifierMinNeighbours {
            get {
                return ((int)(this["CascadeClassifierMinNeighbours"]));
            }
            set {
                this["CascadeClassifierMinNeighbours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Size CascadeClassifierMinSize {
            get {
                return ((global::System.Drawing.Size)(this["CascadeClassifierMinSize"]));
            }
            set {
                this["CascadeClassifierMinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size CascadeClassifierMaxSize {
            get {
                return ((global::System.Drawing.Size)(this["CascadeClassifierMaxSize"]));
            }
            set {
                this["CascadeClassifierMaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int EigenFaceRecognizerNumComponents {
            get {
                return ((int)(this["EigenFaceRecognizerNumComponents"]));
            }
            set {
                this["EigenFaceRecognizerNumComponents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double EigenFaceRecognizerThreshold {
            get {
                return ((double)(this["EigenFaceRecognizerThreshold"]));
            }
            set {
                this["EigenFaceRecognizerThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EigenFaceRecognizerThresholdInfinity {
            get {
                return ((bool)(this["EigenFaceRecognizerThresholdInfinity"]));
            }
            set {
                this["EigenFaceRecognizerThresholdInfinity"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public double DefaultCascadeClassifierScaleFactor {
            get {
                return ((double)(this["DefaultCascadeClassifierScaleFactor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DefaultCascadeClassifierMinNeighbours {
            get {
                return ((int)(this["DefaultCascadeClassifierMinNeighbours"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Size DefaultCascadeClassifierMinSize {
            get {
                return ((global::System.Drawing.Size)(this["DefaultCascadeClassifierMinSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DefaultCascadeClassifierMaxSize {
            get {
                return ((global::System.Drawing.Size)(this["DefaultCascadeClassifierMaxSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int DefaultEigenFaceRecognizerNumComponents {
            get {
                return ((int)(this["DefaultEigenFaceRecognizerNumComponents"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DefaultEigenFaceRecognizerThreshold {
            get {
                return ((double)(this["DefaultEigenFaceRecognizerThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultEigenFaceRecognizerThresholdInfinity {
            get {
                return ((bool)(this["DefaultEigenFaceRecognizerThresholdInfinity"]));
            }
        }
    }
}
