//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAS.ManagementClient.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fa_IR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fa_IR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AAS.ManagementClient.Languages.fa_IR", typeof(fa_IR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند {0} را حذف کن.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف کارمند {0}.
        /// </summary>
        internal static string DeletingEmployee {
            get {
                return ResourceManager.GetString("DeletingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این عمل قابل برگشت نمی باشد، تمام اطلاعات مربوط به کارمند {0} به شماره کارمندی {1} از سیستم حذف می شود، آیا مطمئن هستید؟.
        /// </summary>
        internal static string DeletingEmployeeConfirmation {
            get {
                return ResourceManager.GetString("DeletingEmployeeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند {0} به شماره کارمندی {1} با موفقیت ثبت شد.
        /// </summary>
        internal static string EmployeeHasBeenCreatedSuccessfully {
            get {
                return ResourceManager.GetString("EmployeeHasBeenCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند {0} به شماره کارمندی {1} با موفقیت حذف شد.
        /// </summary>
        internal static string EmployeeHasBeenDeletedSuccessfully {
            get {
                return ResourceManager.GetString("EmployeeHasBeenDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کارمند {0} به شماره کارمندی {1} با موفقیت به روز رسانی شد.
        /// </summary>
        internal static string EmployeeHasBeenUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("EmployeeHasBeenUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در فرم زیر تعدادی خطا وجود دارد.
        /// </summary>
        internal static string FollowingFormContainsErrors {
            get {
                return ResourceManager.GetString("FollowingFormContainsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه مدیریت سیستم تشخیص چهره پیدا نشد.
        /// </summary>
        internal static string FRSManagementClientWasNotFound {
            get {
                return ResourceManager.GetString("FRSManagementClientWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ورودی برای {0} کوتاه است.
        /// </summary>
        internal static string InputTooShort {
            get {
                return ResourceManager.GetString("InputTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرت شماره موبایل اشتباه است.
        /// </summary>
        internal static string InvalidCellphoneNumber {
            get {
                return ResourceManager.GetString("InvalidCellphoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تاریخ اشتباه است.
        /// </summary>
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ایمیل اشتباه است.
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فقط حاوی حروف الفبا و فاصله می تواند باشد.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی باید حاوی 10 رقم باشد.
        /// </summary>
        internal static string InvalidNationalIDFormat {
            get {
                return ResourceManager.GetString("InvalidNationalIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فقط باید حاوی اعداد باشد.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره تلفن اشتباه است.
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول کد پستی ده رقم و فاقد 0 و 2 است.
        /// </summary>
        internal static string InvalidPostalCodeFormat {
            get {
                return ResourceManager.GetString("InvalidPostalCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نامعتبر است.
        /// </summary>
        internal static string IsInvalid {
            get {
                return ResourceManager.GetString("IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند باید حداقل 18 سال داشته باشد.
        /// </summary>
        internal static string OlderThanEighteen {
            get {
                return ResourceManager.GetString("OlderThanEighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس پرسنلی.
        /// </summary>
        internal static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود {0} اجباری است.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای نامشخص در {0}.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
